// Indian Medical Councils - All state medical councils
export const INDIAN_MEDICAL_COUNCILS = [
  { id: 'amchk', name: 'Andhra Pradesh Medical Council' },
  { id: 'ammuk', name: 'Assam Medical Council' },
  { id: 'bmicouncil', name: 'Bihar Medical Council' },
  { id: 'chhattisgarh', name: 'Chhattisgarh Medical Council' },
  { id: 'dcmcgnc', name: 'Delhi Medical Council' },
  { id: 'goamedicalcouncil', name: 'Goa Medical Council' },
  { id: 'gmc', name: 'Gujarat Medical Council' },
  { id: 'haryana', name: 'Haryana Medical Council' },
  { id: 'himachal', name: 'Himachal Pradesh Medical Council' },
  { id: 'jharkhand', name: 'Jharkhand Medical Council' },
  { id: 'kmc', name: 'Karnataka Medical Council' },
  { id: 'kml', name: 'Kerala Medical Council' },
  { id: 'mpmc', name: 'Madhya Pradesh Medical Council' },
  { id: 'mmc', name: 'Maharashtra Medical Council' },
  { id: 'manipur', name: 'Manipur Medical Council' },
  { id: 'meghalaya', name: 'Meghalaya Medical Council' },
  { id: 'mizoram', name: 'Mizoram Medical Council' },
  { id: 'nagaland', name: 'Nagaland Medical Council' },
  { id: 'odisha', name: 'Odisha Medical Council' },
  { id: 'pmc', name: 'Punjab Medical Council' },
  { id: 'rmc', name: 'Rajasthan Medical Council' },
  { id: 'sikkim', name: 'Sikkim Medical Council' },
  { id: 'tmc', name: 'Tamil Nadu Medical Council' },
  { id: 'tgmedical', name: 'Telangana Medical Council' },
  { id: 'tripura', name: 'Tripura Medical Council' },
  { id: 'upmc', name: 'Uttar Pradesh Medical Council' },
  { id: 'uttarakhand', name: 'Uttarakhand Medical Council' },
  { id: 'wbmc', name: 'West Bengal Medical Council' },
  { id: 'nmc', name: 'National Medical Commission (NMC)' },
];

// Indian States for registration state field
export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman & Nicobar Islands', 'Chandigarh', 'Dadra & Nagar Haveli and Daman & Diu',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry',
];
