import { useState, useRef } from 'react';
import { Search, Printer, MessageCircle, CheckCircle2, IndianRupee, CreditCard, Banknote, X, Clock, User } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { usePadStore } from '@/store/usePadStore';
import type { Patient, VisitRecord, AppointmentEntry } from '@/types';
import { PrintPreview } from '@/components/PrintPreview';

// ─── WhatsApp text formatter ──────────────────────────────────────────────────

function buildRxText(
  patient: Patient,
  visit: VisitRecord,
  doctorName: string,
  clinicName: string,
  address: string,
) {
  const lines: string[] = [];
  lines.push(`*${clinicName || doctorName}*`);
  if (address) lines.push(address);
  lines.push('');
  lines.push(`*Patient:* ${patient.name}  |  ${patient.age}y ${patient.gender}`);
  lines.push(`*MRN:* ${patient.mrn}  |  *Date:* ${new Date(visit.date).toLocaleDateString('en-IN')}`);
  lines.push(`*Dr:* ${visit.doctorName}`);
  lines.push('');
  lines.push(`*Diagnosis:* ${visit.diagnosis}`);

  if (visit.drugs.length > 0) {
    lines.push('');
    lines.push('*💊 Medications:*');
    visit.drugs.forEach((d, i) => {
      lines.push(`${i + 1}. ${d.drug} ${d.dose} — ${d.frequency}, ${d.duration}`);
      if (d.instructions) lines.push(`   _(${d.instructions})_`);
    });
  }

  if (visit.advice) {
    lines.push('');
    lines.push(`*Advice:* ${visit.advice}`);
  }

  if (visit.followUp) {
    lines.push(`*Follow-up:* ${visit.followUp}`);
  }

  lines.push('');
  lines.push('_Generated by Vyasa Integrated Healthcare_');
  return lines.join('\n');
}

// ─── Print styles injected into document ─────────────────────────────────────

// ─── Prescription card (print-safe) ──────────────────────────────────────────

function RxCard({ patient, visit, settings }: { patient: Patient; visit: VisitRecord; settings: ReturnType<typeof usePadStore.getState>['settings'] }) {
  return (
    <div className="space-y-3 text-sm text-slate-800 font-sans">
      {/* Header */}
      <div className="border-b-2 border-teal-600 pb-3">
        <div className="text-lg font-bold text-teal-700">{settings.doctorName || 'Doctor'}</div>
        <div className="text-xs text-slate-500">{settings.degrees} {settings.specialty ? `· ${settings.specialty}` : ''}</div>
        {settings.regNumber && <div className="text-xs text-slate-400">Reg: {settings.regNumber}</div>}
        <div className="text-xs text-slate-400 mt-1">{settings.clinicName} {settings.address ? `· ${settings.address}` : ''}</div>
        {settings.phone && <div className="text-xs text-slate-400">📞 {settings.phone}</div>}
      </div>

      {/* Patient info */}
      <div className="grid grid-cols-2 gap-2 text-xs bg-slate-50 rounded p-2">
        <div><span className="text-slate-400">Patient</span><div className="font-semibold">{patient.name}</div></div>
        <div><span className="text-slate-400">MRN</span><div className="font-mono">{patient.mrn}</div></div>
        <div><span className="text-slate-400">Age / Sex</span><div>{patient.age}y {patient.gender}</div></div>
        <div><span className="text-slate-400">Date</span><div>{new Date(visit.date).toLocaleDateString('en-IN')}</div></div>
        {patient.locality && <div className="col-span-2"><span className="text-slate-400">Area</span><div>{patient.locality}</div></div>}
      </div>

      {/* Diagnosis */}
      <div>
        <div className="text-xs font-bold uppercase tracking-widest text-teal-600 mb-1">Diagnosis</div>
        <div className="font-semibold">{visit.diagnosis}</div>
        {visit.chiefComplaint && <div className="text-xs text-slate-500 mt-0.5">CC: {visit.chiefComplaint}</div>}
      </div>

      {/* Drugs */}
      {visit.drugs.length > 0 && (
        <div>
          <div className="text-xs font-bold uppercase tracking-widest text-teal-600 mb-2">Medications</div>
          <div className="space-y-2">
            {visit.drugs.map((d, i) => (
              <div key={i} className="flex gap-2 border-l-2 border-teal-300 pl-2">
                <span className="text-teal-600 font-bold">{i + 1}.</span>
                <div>
                  <div className="font-semibold">{d.drug} <span className="font-normal text-slate-600">{d.dose}</span></div>
                  <div className="text-xs text-slate-500">{d.frequency} · {d.duration} {d.route ? `· ${d.route}` : ''}</div>
                  {d.instructions && <div className="text-xs italic text-slate-400">{d.instructions}</div>}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Advice + Follow-up */}
      {(visit.advice || visit.followUp) && (
        <div className="border-t pt-2 space-y-1">
          {visit.advice && <div className="text-xs"><span className="font-semibold text-slate-600">Advice: </span>{visit.advice}</div>}
          {visit.followUp && <div className="text-xs"><span className="font-semibold text-slate-600">Follow-up: </span>{visit.followUp}</div>}
        </div>
      )}

      {/* Footer */}
      <div className="border-t pt-2 text-right text-xs text-slate-400">
        Signature: ___________________<br />
        <span className="text-teal-600 font-medium">{settings.doctorName}</span>
      </div>
    </div>
  );
}

// ─── Payment Modal ────────────────────────────────────────────────────────────

function PaymentModal({
  appointment,
  onClose,
  onSave,
}: {
  appointment: AppointmentEntry;
  onClose: () => void;
  onSave: (amountPaid: number, mode: 'cash' | 'upi' | 'card', isAdvance: boolean) => void;
}) {
  const totalFee = appointment.consultationFee ?? 0;
  const alreadyPaid = appointment.amountPaid ?? 0;
  const remaining = Math.max(0, totalFee - alreadyPaid);

  const [mode, setMode] = useState<'cash' | 'upi' | 'card'>('cash');
  const [amount, setAmount] = useState(String(remaining || totalFee || ''));
  const [isAdvance, setIsAdvance] = useState(false);

  const parsedAmount = Number(amount);

  function handleSave() {
    if (!parsedAmount || parsedAmount <= 0) return;
    onSave(parsedAmount, mode, isAdvance);
    onClose();
  }

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm p-6 space-y-5">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-bold text-slate-900">Collect Payment</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>
        </div>

        {/* Patient */}
        <div className="bg-slate-50 rounded-xl p-3 text-sm">
          <div className="font-semibold text-slate-800">{appointment.patientName}</div>
          <div className="text-slate-500 text-xs mt-0.5">{appointment.date} · Token {appointment.token ?? '—'}</div>
          {totalFee > 0 && (
            <div className="flex justify-between mt-2 text-xs">
              <span className="text-slate-500">Consultation fee</span>
              <span className="font-semibold">₹{totalFee}</span>
            </div>
          )}
          {alreadyPaid > 0 && (
            <div className="flex justify-between text-xs text-emerald-600">
              <span>Already paid</span>
              <span>−₹{alreadyPaid}</span>
            </div>
          )}
          {totalFee > 0 && (
            <div className="flex justify-between text-xs font-bold border-t mt-1 pt-1 text-slate-700">
              <span>Remaining</span>
              <span>₹{remaining}</span>
            </div>
          )}
        </div>

        {/* Payment type toggle */}
        <div>
          <label className="label mb-2">Payment type</label>
          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={() => setIsAdvance(false)}
              className={`py-2 rounded-lg border text-sm font-medium transition-colors ${!isAdvance ? 'bg-teal-600 border-teal-600 text-white' : 'border-gray-300 text-gray-600 hover:border-teal-400'}`}
            >
              Full Payment
            </button>
            <button
              onClick={() => setIsAdvance(true)}
              className={`py-2 rounded-lg border text-sm font-medium transition-colors ${isAdvance ? 'bg-amber-500 border-amber-500 text-white' : 'border-gray-300 text-gray-600 hover:border-amber-400'}`}
            >
              Advance / Token
            </button>
          </div>
          {isAdvance && (
            <p className="text-xs text-amber-600 mt-1">Token advance — balance due at consultation</p>
          )}
        </div>

        {/* Amount */}
        <div>
          <label className="label mb-1">Amount (₹)</label>
          <input
            type="number"
            min="1"
            className="input text-lg font-bold"
            value={amount}
            onChange={e => setAmount(e.target.value)}
            autoFocus
          />
        </div>

        {/* Quick amounts */}
        {totalFee > 0 && (
          <div className="flex gap-2 flex-wrap">
            {[100, 200, 300, totalFee].filter((v, i, a) => a.indexOf(v) === i).map(v => (
              <button key={v} onClick={() => setAmount(String(v))}
                className="text-xs px-3 py-1.5 border rounded-lg hover:bg-teal-50 hover:border-teal-400 text-slate-600 transition-colors">
                ₹{v}
              </button>
            ))}
          </div>
        )}

        {/* Payment mode */}
        <div>
          <label className="label mb-2">Payment mode</label>
          <div className="grid grid-cols-3 gap-2">
            {([
              { key: 'cash' as const, label: 'Cash', icon: Banknote },
              { key: 'upi' as const, label: 'UPI', icon: MessageCircle },
              { key: 'card' as const, label: 'Card', icon: CreditCard },
            ]).map(({ key, label, icon: Icon }) => (
              <button key={key} onClick={() => setMode(key)}
                className={`flex flex-col items-center gap-1 py-2 rounded-xl border text-xs font-medium transition-colors ${mode === key ? 'bg-teal-600 border-teal-600 text-white' : 'border-gray-300 text-gray-600 hover:border-teal-400'}`}>
                <Icon className="w-4 h-4" />
                {label}
              </button>
            ))}
          </div>
        </div>

        <button
          onClick={handleSave}
          disabled={!parsedAmount || parsedAmount <= 0}
          className="w-full btn-primary py-3 text-base disabled:opacity-40"
        >
          <IndianRupee className="w-4 h-4" />
          Collect ₹{parsedAmount || 0}
        </button>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function PrescriptionViewerPage() {
  const { patients, visits, appointments, updateAppointment } = useAppStore();
  const { settings } = usePadStore();
  const printRef = useRef<HTMLDivElement>(null);

  const [search, setSearch] = useState('');
  const [selectedVisit, setSelectedVisit] = useState<{ patient: Patient; visit: VisitRecord } | null>(null);
  const [paymentApt, setPaymentApt] = useState<AppointmentEntry | null>(null);
  const [showPrint, setShowPrint] = useState(false);

  // Receptionist sees only visits from the last 24 hours
  const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  const todayVisitsOnly = (pid: string) =>
    (visits[pid] ?? []).filter(v => v.date >= cutoff);

  // Patients who have a visit in the last 24h
  const consultedPatients = patients.filter(p => todayVisitsOnly(p.id).length > 0);

  const filtered = consultedPatients.filter(p =>
    p.name.toLowerCase().includes(search.toLowerCase()) ||
    p.mrn.toLowerCase().includes(search.toLowerCase())
  );

  // Get today's appointments for payment marking
  const todayStr = new Date().toISOString().slice(0, 10);
  const todayApts = appointments.filter(a => a.date === todayStr);

  // Map a stored visit into the PrintPreview "draft" shape so the receptionist prints
  // the SAME customised PAD (logo + QR + branding) the doctor generates.
  function visitToDraft(v: VisitRecord) {
    const vs: any = (v as any)?.vitalsSnapshot ?? {};
    return {
      chiefComplaint: (v as any)?.chiefComplaint ?? '',
      hopi: (v as any)?.hopi ?? '',
      diagnosis: (v as any)?.diagnosis ?? '',
      icdCode: (v as any)?.icdCode ?? '',
      secondaryDx: (v as any)?.secondaryDx ?? '',
      rxRows: ((v as any)?.drugs ?? []).map((d: any, i: number) => ({
        id: String(i),
        form: d.form ?? 'Tab',
        drug: d.drug ?? '',
        dose: d.dose ?? '',
        strength: d.strength ?? '',
        puffs: d.puffs ?? '',
        route: d.route ?? 'Oral',
        frequency: d.frequency ?? '',
        duration: d.duration ?? '',
        instructions: d.instructions ?? '',
      })),
      vitals: {
        bp: vs.bp ?? '', hr: vs.hr ?? '', temp: vs.temp ?? '', spo2: vs.spo2 ?? '',
        weight: vs.weight ?? '', height: vs.height ?? '', rr: vs.rr ?? '',
      },
      investigation: (v as any)?.investigation ?? '',
      advice: (v as any)?.advice ?? '',
      followUp: (v as any)?.followUp ?? '',
      referredTo: (v as any)?.referral?.specialty ?? '',
    };
  }

  function handleWhatsApp(patient: Patient, visit: VisitRecord) {
    const text = buildRxText(patient, visit, settings.doctorName, settings.clinicName, settings.address);
    const phone = patient.phone?.replace(/\D/g, '') ?? '';
    const url = phone
      ? `https://wa.me/91${phone.slice(-10)}?text=${encodeURIComponent(text)}`
      : `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noopener');
  }

  function handleCollectPayment(amountPaid: number, mode: 'cash' | 'upi' | 'card', _isAdvance: boolean) {
    if (!paymentApt) return;
    const prevPaid = paymentApt.amountPaid ?? 0;
    updateAppointment(paymentApt.id, {
      amountPaid: prevPaid + amountPaid,
      paymentMode: mode,
      status: 'confirmed',
    });
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="page-title">Prescriptions</h1>
          <p className="page-subtitle">View, print, and share patient prescriptions</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Left: patient list */}
        <div className="lg:col-span-1 space-y-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              className="input pl-9"
              placeholder="Search patients…"
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </div>

          <div className="space-y-2 max-h-[60vh] overflow-y-auto pr-1">
            {filtered.map(p => {
              const isSelected = selectedVisit?.patient.id === p.id;
              const apt = todayApts.find(a => a.patientId === p.id);
              const isPaid = apt && (apt.amountPaid ?? 0) > 0;

              return (
                <button
                  key={p.id}
                  onClick={() => { const v = todayVisitsOnly(p.id)[0]; v && setSelectedVisit({ patient: p, visit: v }); }}
                  className={`w-full text-left p-3 rounded-xl border transition-all ${
                    isSelected ? 'border-teal-500 bg-teal-50' : 'border-slate-200 bg-white hover:border-teal-300 hover:bg-slate-50'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="min-w-0">
                      <div className="font-semibold text-slate-900 text-sm truncate">{p.name}</div>
                      <div className="text-xs text-slate-500">{p.mrn} · {p.age}y</div>
                      {p.locality && <div className="text-xs text-slate-400">{p.locality}</div>}
                    </div>
                    <div className="flex flex-col items-end gap-1 flex-shrink-0">
                      {todayVisitsOnly(p.id)[0] && (
                        <span className="text-[10px] bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded">
                          {new Date(todayVisitsOnly(p.id)[0].date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}
                        </span>
                      )}
                      {apt && (
                        <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${isPaid ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
                          {isPaid ? `Paid ₹${apt.amountPaid}` : 'Unpaid'}
                        </span>
                      )}
                    </div>
                  </div>
                </button>
              );
            })}
            {filtered.length === 0 && (
              <div className="text-center py-10 text-slate-400 text-sm">No consulted patients found</div>
            )}
          </div>

          {/* Payment section for today's appointments */}
          {todayApts.length > 0 && (
            <div className="border rounded-xl p-3 space-y-2">
              <div className="text-xs font-bold uppercase tracking-widest text-slate-500 flex items-center gap-1.5">
                <IndianRupee className="w-3.5 h-3.5" /> Today's Payments
              </div>
              {todayApts.map(apt => {
                const paid = apt.amountPaid ?? 0;
                const fee = apt.consultationFee ?? 0;
                const fullyPaid = fee > 0 && paid >= fee;
                return (
                  <div key={apt.id} className="flex items-center justify-between text-xs">
                    <div>
                      <div className="font-medium text-slate-800">{apt.patientName}</div>
                      <div className="text-slate-400 flex items-center gap-1"><Clock className="w-3 h-3" />{apt.time} · Token {apt.token ?? '—'}</div>
                    </div>
                    <button
                      onClick={() => setPaymentApt(apt)}
                      className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-colors ${
                        fullyPaid
                          ? 'bg-emerald-100 text-emerald-700'
                          : paid > 0
                          ? 'bg-amber-100 text-amber-700'
                          : 'bg-slate-100 text-slate-600 hover:bg-teal-50 hover:text-teal-700'
                      }`}
                    >
                      {fullyPaid ? <><CheckCircle2 className="w-3 h-3 inline mr-0.5" />Paid</> : paid > 0 ? `₹${paid} adv.` : 'Collect'}
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right: prescription preview */}
        <div className="lg:col-span-2">
          {selectedVisit ? (
            <div className="card p-5 space-y-4">
              {/* Actions */}
              <div className="flex items-center justify-between gap-3 flex-wrap">
                <div className="flex items-center gap-2 text-sm text-slate-500">
                  <User className="w-4 h-4" />
                  <span className="font-semibold text-slate-800">{selectedVisit.patient.name}</span>
                  <span>·</span>
                  <span>{selectedVisit.visit.date}</span>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => handleWhatsApp(selectedVisit.patient, selectedVisit.visit)}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
                  >
                    <MessageCircle className="w-4 h-4" />
                    WhatsApp
                  </button>
                  <button
                    onClick={() => setShowPrint(true)}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-slate-700 text-white rounded-lg hover:bg-slate-800 transition-colors"
                  >
                    <Printer className="w-4 h-4" />
                    Print PDF
                  </button>
                </div>
              </div>

              {/* Visits selector — only today's visits for receptionist */}
              {todayVisitsOnly(selectedVisit.patient.id).length > 1 && (
                <div className="flex gap-2 flex-wrap">
                  {todayVisitsOnly(selectedVisit.patient.id).map(v => (
                    <button
                      key={v.id}
                      onClick={() => setSelectedVisit({ patient: selectedVisit.patient, visit: v })}
                      className={`text-xs px-2.5 py-1 rounded-lg border transition-colors ${
                        selectedVisit.visit.id === v.id
                          ? 'bg-teal-600 border-teal-600 text-white'
                          : 'border-slate-300 text-slate-600 hover:border-teal-400'
                      }`}
                    >
                      {new Date(v.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}
                    </button>
                  ))}
                </div>
              )}

              {/* Prescription card */}
              <div ref={printRef} className="border rounded-xl p-5 bg-white">
                <RxCard
                  patient={selectedVisit.patient}
                  visit={selectedVisit.visit}
                  settings={settings}
                />
              </div>
            </div>
          ) : (
            <div className="card p-12 text-center text-slate-400">
              <Printer className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <div className="font-medium">Select a patient to view prescription</div>
              <div className="text-sm mt-1">Print as PDF or share via WhatsApp</div>
            </div>
          )}
        </div>
      </div>

      {/* Payment modal */}
      {paymentApt && (
        <PaymentModal
          appointment={paymentApt}
          onClose={() => setPaymentApt(null)}
          onSave={handleCollectPayment}
        />
      )}

      {/* Same customised PAD (logo + QR + branding) the doctor prints/shares */}
      {showPrint && selectedVisit && (
        <PrintPreview
          patient={selectedVisit.patient}
          draft={visitToDraft(selectedVisit.visit) as any}
          pad={settings}
          onClose={() => setShowPrint(false)}
          onWhatsApp={() => handleWhatsApp(selectedVisit.patient, selectedVisit.visit)}
        />
      )}
    </div>
  );
}
